### ISSUE TITLE
Compatible with Nova 2.0.9 ? Composer error

### ISSUE THREAD

**Issue by eugenevdm** [kirschbaum-development/nova-comments#12]
I get a composer error when trying to install this with Nova (2.0.9):

`✗ composer require kirschbaum-development/nova-comments
Using version ^1.0 for kirschbaum-development/nova-comments
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - kirschbaum-development/nova-comments 1.0.1 requires laravel/nova ^2.0 -> no matching package found.
    - kirschbaum-development/nova-comments 1.0.0 requires laravel/nova ^2.0 -> no matching package found.
    - Installation request for kirschbaum-development/nova-comments ^1.0 -> satisfiable by kirschbaum-development/nova-comments[1.0.0, 1.0.1].`

**Comment by brandonferens** [comment]
@eugenevdm Are you still having this issue or has it been resolved?

**Comment by brandonferens** [comment]
@eugenevdm It appears this is irrelevant now.
