### ISSUE TITLE
Show Comments inline in index view

### ISSUE THREAD

**Issue by kosmonowt** [kirschbaum-development/nova-comments#19]
I suggest to add a feature that shows the latest N comments also in the index view and gives space to a modal to see all comments.

**Comment by brandonferens** [comment]
@kosmonowt I like the idea of showing the number of comments.

I am curious what exactly you have in mind regarding the modal with comments. Are you thinking a scrollable modal with all the comments?

**Comment by kosmonowt** [comment]
Hi Brandon,
sorry for not answering for so long.

In another system, I've had it somehow like that:

![Bildschirmfoto 2020-05-06 um 15 42 20](https://user-images.githubusercontent.com/1159594/81184025-2ff7b380-8fb0-11ea-8dc4-62e562a0d182.png)

Deriving from that I think it would be possible to come along with some accordeon-style or modal-style view of the recent comments, probably by clicking on a balloon or so.

Just something that makes it easier to see the comments that have been dropped / or at least an indicator that comments exist.

**Comment by adammparker** [comment]
@kosmonowt Curious if this is still something you think makes sense to add to this package. I think we'd be open to a PR if someone wanted to add this, but it might get complicated pretty quickly and thus harder to maintain the package which is pretty simple currently.
