### ISSUE TITLE
Error when comment without commentable_type

### ISSUE THREAD

**Issue by codealliance** [kirschbaum-development/nova-comments#28]
when comment is created by general form https://big.local/resources/comments/new
i get this error when calling index https://big.local/resources/comments

db looks like this:  https://www.dropbox.com/s/xslhxw2h219994u/Screenshot%202020-07-26%2016.10.59.png?dl=0

error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_comments.' in 'where clause' (SQL: select * from `nova_comments` where `nova_comments`.`` = 0 limit 1) {"userId":37,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nova_comments.' in 'where clause' (SQL: select * from `nova_comments` where `nova_comments`.`` = 0 limit 1) at /Users/behrangalavi/PhpstormProjects/big-erp-laravel/doc_root/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)

**Comment by adammparker** [comment]
@codealliance I see, yeah this actually makes sense I think. Unfortunately, the built-in resource only makes sense if you want view/edit/delete functionality. Creating a new comment requires a morphTo related entity (i.e. currently we don't allow the morph "commentable" to be `null`.

If you extend the `Comment` resource we provide you can specify the fields you want. For example, we include:

```php
MorphTo::make('Commentable')->onlyOnIndex(),
```

But, you would want to do something like this:

```php
MorphTo::make('Commentable')->types([...]),
```

Refer to this part of the docs: https://nova.laravel.com/docs/4.0/resources/relationships.html#morphto

The other option you might have is to add a new migration in the project where you've added the package that updates the morph columns on the `nova_comments` table to be nullable.
