### ISSUE TITLE
Support for Nova v4.x

### ISSUE THREAD

**Issue by centgart** [kirschbaum-development/nova-comments#47]
Since this repository hasn't been updated since March 2020, and current version does not support Laravel Nova v4.x, I've forked the repo and made necessary changes.

Primary change: fixed Comment Resource to match the new Nova 4 signature with NovaRequest instead of Request
Description of the major changes from Nova 4: https://nova.laravel.com/docs/4.0/upgrade.html#nova-request

My fork of nova-comments with support for Nova 4: https://github.com/amukhin-cyberhull/nova-comments

**Comment by anthony-brindley** [comment]
Thanks for this @centgart - unfortunately there seems to be a problem with the DateTime field (https://bit.ly/3LFIHQD)? Any thoughts on a resolution?

**Comment by anthony-brindley** [comment]
This presents itself when including the CommentsPanel in the resource

**Comment by centgart** [comment]
@anthony-brindley please see tag 1.1.3 in my repo, I've managed to fix the issue with DateTime field for CommentsPanel tool.

However, looks like Commenter tool is still not working (just not appearing on resource detail page for some reason). Digging into that to figure out the issue.

**Comment by anditsung** [comment]
is this package still active and accepting PR?

**Comment by chrillep** [comment]
@brandonferens ping! :)

**Comment by brandonferens** [comment]
Thanks for the reminder @chrillep. It's is on my todo list.

**Comment by chrillep** [comment]
@centgart could you create a PR here ?
