### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by pasxel** [kirschbaum-development/nova-comments#55]
Added comments are not showing. I can see in browser console error `ReferenceError: _ is not defined`.
Package version: 4.0.0
Laravel: 9.31
Laravel Nova: 4.15.1

Looks like problem with lodash importing.

Steps for reproducing:
1. `composer require kirschbaum-development/nova-comments`
2. Run migration: `php artisan migrate`
3. Adding `use Commentable;` to Model.
4. Adding to Nova resource : 
```php

public function fields(Request $request)
    {
        return [
            // ...
            HasMany::make('Comments', 'comments', Comment::class)
                ->hideFromDetail()
                ->hideFromIndex(),
            Commenter::make(),
          //
          ];
```
5. Go to Resource and add any comment.
6. As a result, Comments block will be empty and browser console shows `ReferenceError: _ is not defined`

**Comment by adammparker** [comment]
Resolved in 4.0.1, thanks!
