### ISSUE TITLE
displayInNavigation

### ISSUE THREAD

**Issue by gueroultalexandre** [kirschbaum-development/nova-comments#6]
Hi,
First, thans yo tou guys :)

I need to understand, why are you displaying comment ressource in sidebar navigation ?
If we can fast adding comments in other resources details, why is this useful in nav ?

Im in case where i need to remove comment resource from navigation sideba and i can't overide your comment nova resource. Or im i missing somethink ?

**Comment by brandonferens** [comment]
@gueroultalexandre I will look into this and see if there are some good solutions for this. I'll let you know what I come up with.

**Comment by brandonferens** [comment]
This feature has been released in tag `1.0.2`
