### ISSUE TITLE
How can I strip html tags from the comments?

### ISSUE THREAD

**Issue by mgolshan** [kirschbaum-development/nova-comments#70]
When we add a new comment, we can easily inject scripts and tags.
How can I strip the input to be stored as plain string?

**Comment by luisdalmolin** [comment]
It does that by default on the new version now (just upgrade), or you can customize what you want to do: https://github.com/kirschbaum-development/nova-comments?tab=readme-ov-file#customizing-the-comment

**Comment by mgolshan** [comment]
Awesome!
It works.
Thanks.

May I know where I can add `Comment::whenCreating` piece of code if needed?
I was wondering if I could emit an event when a comment is created. It'll be useful for actions like sending notifications.

**Comment by luisdalmolin** [comment]
You can add in the service provider
